apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
spec:
    replicas: 2 # Replicas of Nodes 
    selector: 
        matchLabels:  
            app: nginx
    template: # Template for Pods (its a normal pod specification)
        metadata:
            labels:
                app: nginx
        spec: 
            containers:
            - name: nginx
              image: nginx:1.14.2
              ports:
              - containerPort: 80