apiVersion: v1
kind: Pod
metadata:
	name: init-container
spec: 
	containers:
	- name: nginx
		image: nginx:stable
	initContainers:
	- name: busybox
		image: busybox:stable
		command: ['sh', '-c', 'sleep 60']