FROM mcr.microsoft.com/mssql/server:latest

ENV ACCEPT_EULA=Y \
    SA_PASSWORD=DeinKomplexesPasswort123! \
    MSSQL_PID=Developer \
    MSSQL_USER=DeinAdminName \
    MSSQL_PASSWORD=DeinAdminPasswort123!


EXPOSE 1433
