apiVersion: batch/v1
kind: CronJob
metadata: 
	name: my-cronjob
spec: # Job Specification
	schedule: "*/1 * * * *" # Trigger
	jobTemplate: 
		spec: 
			containers:
			- name: print
				image: busybox:stable
				command: ["echo", "This is a test!"]
			restartPolicy: Never # Its a job to run one time
	backoffLimit: 4
	activeDeadlineSeconds: 10 # maximum time a job is allowed to run (after 10 sec kubernetes kills this job)