apiVersion: v1
kind: Pod
metadata: 
	name: sidecar-test
spect:
	containers:
	- name: writer # Container 1
		image: busybox:stable
		command: ['sh', '-c', 'echo "The writer wrote this!"> /output/data.txt; while true; do sleep 5; done ']
		volumeMounts:
		- name: shared
			mountPath: /output
	- name: sidecar # Container 2
		image: busybox:stable
		command: ['sh', '-c', 'while true; do cat /input/data.txt; sleep 5; done']
		volumeMounts: 
		- name: shared
			mountPath: /input
	volumes:
	- name: shared 
		emptyDir: {}