apiVersion: v1 
kind: Pod
metadata:
	name: hostpath-volume-test
spec:
	restartPolicy: OnFailure
	containers:
	- name: busybox
		image: busybox:stable
		command: ['sh', '-c', 'cat /data/data.txt'] # on the host
		volumeMounts: # List of volume mounts
		- name: host-data
			mountPath: /data
	volumes:
	- name: host-data
		hostPath:
			path: /etc/hostPath # Location of the worker node
			type: Directory # there is File, FileOrCreate, DirectoryOrCreate